referral_system/api/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

from .views import UsersViewSet, authorization, invitation, verification

app_name = 'api'

router = DefaultRouter()
router.register(r'user', UsersViewSet, basename='users')

urlpatterns = [
    path('auth/', authorization),
    path('verify/', verification),
    path('user/invitation/', invitation),
    path('docs/', TemplateView.as_view(
        template_name='swagger.html',
        extra_context={'schema_url': 'openapi-schema'}
    ), name='swagger-ui'),
    path('', include(router.urls)),
]

referral_system/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    path('', include('frontend.urls', namespace='frontend'))
]

referral_system/frontend/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import main, profile, signup, verification

app_name = 'frontend'


urlpatterns = [
    path('', main, name='main'),
    path('signup/', signup, name='signup'),
    path('verify/', verification, name='verification'),
    path('me/', profile, name='me'),
    path('logout/', LogoutView.as_view(), name='logout')
]

referral_system/frontend/models.py
from config.constants import INVITE_CODE_LENGTH, MAX_LENGTH_PHONE_NUMBER
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.validators import MinLengthValidator, RegexValidator
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    """Кастомная модель юзеров, которая основана на модели «AbstractBaseUser».

    Поля модели:
      - phonenumber: номер телефона.
      - invite_code: инвайт-код
      - invitation: активация инвайт-кода
    """

    phonenumber = PhoneNumberField(
        validators=[RegexValidator(
            r'^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$')
        ],
        max_length=MAX_LENGTH_PHONE_NUMBER, unique=True,
        verbose_name='Номер телефона'
    )
    invite_code = models.CharField(
        validators=[MinLengthValidator(INVITE_CODE_LENGTH)],
        max_length=INVITE_CODE_LENGTH, verbose_name='Инвайт-код',
        unique=True, blank=True
    )
    invitation = models.ManyToManyField(
        to='self', symmetrical=False,
        related_name='invitations', verbose_name='Активация инвайт-кода'
    )
    is_staff = models.BooleanField(
        default=False, verbose_name='Статус администратора'
    )
    is_superuser = models.BooleanField(
        default=False, verbose_name='Статус суперпользователя'
    )

    USERNAME_FIELD = 'phonenumber'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    class Meta:
        ordering = ('-id',)
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return str(self.phonenumber)

referral_system/frontend/forms.py
from config.scripts import editing_phone, form_html
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.forms import CharField, Form, TextInput
from phonenumber_field.formfields import PhoneNumberField

from .models import CustomUser

User = get_user_model()


class InviteForm(Form):
    """Форма для отправки инвайт-кода."""

    def __init__(self, *args, **kwargs):
        """
        Переопределил конструктор, что-бы можно было передать
        в форму информацию о запросе(request).
        """

        self.request = kwargs.pop('request')
        super(InviteForm, self).__init__(*args, **kwargs)

    invite_code = CharField(
        widget=TextInput(attrs={
            'placeholder': 'Введите инвайт-код',
            'class': 'form-control me-sm-2 me-2'}
        ),
        required=True,
        help_text='Вы можете отправить только один инвайт-код.')

    def clean_invite_code(self):
        """Валидация инвайт-кода.

        Проверка на существование инвайт-кода.
        Запрет на отправку инвайт-кода самому себе.
        Проверка на количество отправленных приглашений(не больше одного).
        """

        data = self.cleaned_data.get('invite_code')
        user = CustomUser.objects.filter(invite_code=data)

        if not user:
            raise ValidationError('Вы ввели неверный инвайт-код')

        elif user.get(invite_code=data) == self.request.user:
            raise ValidationError('Вы не можете отправить приглашение себе.')

        elif self.request.user.invitations.all():
            raise ValidationError('Вы уже отправили одно приглашение.')

        return data


class VerifyForm(Form):
    """Форма для sms-верификации/регистрации.

    Если пользователь входит на сайт первый раз, он
    будет добавлен в БД, после подтверждения sms.
    """

    def __init__(self, *args, **kwargs):
        """
        Переопределил конструктор, что-бы можно было передать
        в форму информацию о запросе(request).
        """

        self.request = kwargs.pop("request")
        super(VerifyForm, self).__init__(*args, **kwargs)

    code = CharField(
        widget=TextInput(attrs={
            'placeholder': 'Введите смс-код',
            'class': 'form-control',
            'id': 'floatingInput'}
        ),
        required=True,
        label='Введите смс-код')

    def as_custom(self):
        return form_html(self)

    def clean_code(self):
        """Валидация смс-кода. Проверка, что пользователь введёт верный код."""

        data = self.cleaned_data.get('code')
        if data != self.request.session.get('code'):
            raise ValidationError('Вы ввели неверный смс-код.')
        return data

    def save(self):
        """Метод для сохранения пользователей в БД."""

        phone = str(self.request.session.get('phone'))
        user = CustomUser.objects.filter(phonenumber=phone)

        if not user:
            user = CustomUser.objects.create_user(phone)
            return user

        phone = editing_phone(phone) if phone[0] == '8' else phone
        user = user.get(phonenumber=phone)
        user.save()
        return user


class PhoneForm(Form):
    """Форма для ввода номера телефона."""

    phonenumber = PhoneNumberField(
        widget=TextInput(attrs={
            'placeholder': 'Введите номер телефона',
            'class': 'form-control',
            'id': 'floatingInput'}
        ),
        required=True,
        label='Номер телефона')

    phonenumber.error_messages['invalid'] = (
        'Введите корректный номер телефона например, 83011234567, или '
        'номер с префиксом международной связи.')

    def as_custom(self):
        return form_html(self)

referral_system/frontend/views.py
from config.scripts import auth_code_generator
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.views.decorators.http import require_http_methods

from .forms import InviteForm, PhoneForm, VerifyForm
from .models import CustomUser


@require_http_methods(['GET'])
def main(request):
    """Главная страница."""

    users = CustomUser.objects.all()
    paginator = Paginator(users, 6)
    page_obj = paginator.get_page(request.GET.get('page'))
    template = 'main.html'
    context = {
        'users': users,
        'page_obj': page_obj}
    return render(request, template, context)


@require_http_methods(['GET', 'POST'])
def signup(request):
    """Страница с формой для ввода номера."""

    form_class = PhoneForm(request.POST or None)
    template_name = 'signup.html'
    context = {
        'form': form_class}

    if request.user.is_authenticated:
        return redirect('frontend:main')

    if request.method != "POST":
        return render(request, template_name, context)

    if form_class.is_valid():
        phone = request.POST.get('phonenumber')
        request.session['phone'] = phone
        request.session['code'] = auth_code_generator()
        request.session.set_expiry(300)
        return redirect('frontend:verification')
    return render(request, template_name, context)


@require_http_methods(['GET', 'POST'])
def verification(request):
    """Страница с формой для sms-верификации/входа."""

    if (
        request.user.is_authenticated or
        not request.session.get('code') or
        not request.session.get('phone')
    ):
        return redirect('frontend:signup')

    code = request.session.get('code')
    form_class = VerifyForm(request.POST or None, request=request)
    template = 'verify.html'
    context = {
        'form': form_class,
        'code': code}

    if request.method != "POST":
        return render(request, template, context)

    if form_class.is_valid():
        user = form_class.save()
        request.session.flush()
        login(request, user)
        return redirect('frontend:main')

    return render(request, template, context)


@require_http_methods(['GET', 'POST'])
@login_required
def profile(request):
    """Профиль пользователя, с формой для отправки инвайт-кода."""

    form_class = InviteForm(request.POST or None, request=request)
    template = 'profile.html'
    context = {
        'user': request.user,
        'form': form_class}

    if request.method != "POST":
        return render(request, template, context)

    if form_class.is_valid():
        invite_code = request.POST.get("invite_code")
        user = CustomUser.objects.get(invite_code=invite_code)
        request.user.invitations.add(user)
        return redirect('frontend:me')

    return render(request, template, context)

referral_system/frontend/templates/includes/header.html
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark" style="border: none">
  <div class="container">
    <a class="navbar-brand main_name
      {% if request.resolver_match.view_name  == 'frontend:main' %}
        active" style="color: #fd9730;
      {% endif %}"
      href="{% url 'frontend:main' %}">ReferralSystem
    </a>
    <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item additional_name">
            <a class="nav-link
              {% if view_name  == 'frontend:main' %}
                active" style="color: #fd9730;
              {% endif %}"
              href="{% url 'frontend:main' %}">
                ReferralSystem
            </a>
          </li>
          {% if user.is_authenticated %}
            <li class="contents nav-item">
              <a class="spacing nav-link
                {% if view_name  == 'frontend:me' %}
                  active" style="color: #fd9730;
                {% endif %}"
                href="{% url 'frontend:me' %}">
                  {{  user.phonenumber  }}
              </a>
            </li>
            <li class="contents nav-item">
              <a class="nav-link" style="display: inline-block;" href="{% url 'frontend:logout' %}">
                Выход
              </a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="contents nav-link
                {% if view_name  == 'frontend:signup' or view_name == 'frontend:verification' %}
                  active" style="color: #fd9730;
                {% endif %}"
                href="{% url 'frontend:signup' %}">
                  Войти
              </a>
            </li>
          {% endif %}
        {% endwith %}
      </ul>
    </div>
  </div>
</nav>

referral_system/frontend/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination  pagination-lg"
  style="--bs-pagination-hover-bg: #fd6a30;
         --bs-pagination-focus-bg: #fd6a30;
         --bs-pagination-focus-color: #fff;
         --bs-pagination-focus-box-shadow: none">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <span class="page-link" style="background-color: #fd9730; border-color: #fd9730">{{ i }}</span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          &raquo;
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}